# Feed Forward

In [3]:
# import library numpy
import numpy as np

# membuat fungsi sigmoid untuk normalisasi input
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# input dataset
training_input = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

# output dataset
training_output = np.array([[0,1,1,0]]).T

# membuat random number untuk perhitungan
np.random.seed(5)

# inisialisasi bobot/weights secara random (weights matriks)
#weights = np.random.random((3,1))
weights = [[9], [0], [-4]]

print('Bobot/weigths random awal: ')
print(weights)

# Mendefinisikan layer input
input_layer = training_input
    
# Normalize the product of the input layer with the synaptic weights
bias = 1
input_weights = np.dot(input_layer, weights) + bias
output = sigmoid(input_weights)

# menghitung error
error = training_output - output

print("Output :")
print(output)

print('error :')
print(error)

Bobot/weigths random awal: 
[[9], [0], [-4]]
Output :
[[0.04742587]
 [0.99752738]
 [0.99752738]
 [0.04742587]]
error :
[[-0.04742587]
 [ 0.00247262]
 [ 0.00247262]
 [-0.04742587]]


In [4]:
sigmoid(-9)

0.00012339457598623172

# Back Propagation

In [5]:
# import library numpy
import numpy as np

# membuat fungsi sigmoid untuk normalisasi input
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Membuat fungsi sigmoid derivatif untuk update bobot/weight synapsis
def sigmoid_derivative(x):
    return x * (1 - x)

# input dataset
training_input = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

# output dataset
training_output = np.array([[0, 1, 1, 0]]).T

# membuat random number untuk perhitungan
np.random.seed(1)

# inisialisasi bobot/weights secara random (weights matriks)
weights = 2 * np.random.random((3,1)) - 1

print('Bobot/weigths random awal: ')
print(weights)

# menentukan jumlah iterasi
for iteration in range(10000):

    # Mendefinisikan layer input
    input_layer = training_input
    
    # Perkalian input (x) dengan bobot/weights (w)
    bias = 0.1
    input_weights = np.dot(input_layer, weights) + bias

    # Penerapan activation function sigmoid
    output = sigmoid(input_weights)

    # menghitung error
    error = training_output - output

    # Adjustments weight pada synapsis dengan fungsi derivatif sigmoid
    adjustment = error * sigmoid_derivative(output)

    # update weights
    weights += np.dot(input_layer.T, adjustment)

print('Weights setelah training: ')
print(weights)

print("Output setelah training:")
print(output)


Bobot/weigths random awal: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Weights setelah training: 
[[ 9.67296836]
 [-0.20788535]
 [-4.72959938]]
Output setelah training:
[[0.00966485]
 [0.99211934]
 [0.99358906]
 [0.00786502]]


## New Data

In [6]:
input_data = [[1, 0, 0]]

#weights = [[9], [0], [-4]]

bias = 1
input_weights = np.dot(input_data, weights) + bias
output = sigmoid(input_weights)

print("Output :")
print(output)

Output :
[[0.99997684]]


# ANN menggunakan TensorFlow

In [7]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

model = keras.Sequential()
input_layer = keras.layers.Dense(3, input_dim=3, activation='sigmoid')
model.add(input_layer)
output_layer = keras.layers.Dense(1, activation='sigmoid')
model.add(output_layer)

sgd = keras.optimizers.SGD(lr=1)
model.compile(optimizer=sgd, loss='binary_crossentropy')

# input dataset
x = np.array([[0,0,1],
              [1,1,1],
              [1,0,1],
              [0,1,1]])

# output dataset
y = np.array([[0],[1],[1],[0]])

model.fit(x, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 672ms/step - loss: 1.1776
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.8622
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7535
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7182
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7033
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6943
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6870
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6803
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6737
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6672
Epoch 11/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6605
Epoch 12/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6537
Epoch 13/100
1/1 [==============================] - 0s 9ms/

In [8]:
results = model.predict([[0,0,1]])
print(results)

[[0.07730827]]
